// Arreglo de URLs de las banderas //
const banderas = {
  tonoto: "https://preview.redd.it/about-ados-new-profile-picture-v0-14f0na8r81ce1.jpg?width=640&crop=smart&auto=webp&s=b356a50938e19c4b01e1f80fd4d20411589399b2",
  afg: "https://flagcdn.com/w320/af.png",
  alb: "https://flagcdn.com/w320/al.png",
  and: "https://flagcdn.com/w320/ad.png",
  antybarb: "https://flagcdn.com/w320/ag.png",
  ar: "https://flagcdn.com/w320/ar.png",
  arsau: "https://flagcdn.com/w320/sa.png",
  arm: "https://flagcdn.com/w320/am.png",
  aze: "https://flagcdn.com/w320/az.png",
  ban: "https://flagcdn.com/w320/bd.png",
  bar: "https://flagcdn.com/w320/bh.png",
  bel: "https://flagcdn.com/w320/bz.png",
  belga: "https://flagcdn.com/w320/be.png",
  birr: "https://flagcdn.com/w320/by.png",
  bosher: "https://flagcdn.com/w320/ba.png",
  bol: "https://flagcdn.com/w320/bo.png",
  bra: "https://flagcdn.com/w320/br.png",
  brb: "https://flagcdn.com/w320/bb.png",
  brm: "https://flagcdn.com/w320/mm.png",
  bru: "https://flagcdn.com/w320/bn.png",
  but: "https://flagcdn.com/w320/bt.png",
  cam: "https://flagcdn.com/w320/kh.png",
  can: "https://flagcdn.com/w320/ca.png",
  cata: "https://flagcdn.com/w320/qa.png",
  chi: "https://flagcdn.com/w320/cl.png",
  chn: "https://flagcdn.com/w320/cn.png",
  cn: "https://flagcdn.com/w320/kp.png",
  col: "https://flagcdn.com/w320/co.png",
  cos: "https://flagcdn.com/w320/cr.png",
  cub: "https://flagcdn.com/w320/cu.png",
  dinm: "https://flagcdn.com/w320/dk.png",
  dom: "https://flagcdn.com/w320/dm.png",
  ecu: "https://flagcdn.com/w320/ec.png",
  elsa: "https://flagcdn.com/w320/sv.png",
  eu: "https://flagcdn.com/w320/us.png",
  est: "https://flagcdn.com/w320/ee.png",
  fin: "https://flagcdn.com/w320/fi.png",
  fr: "https://flagcdn.com/w320/fr.png",
  gr: "https://flagcdn.com/w320/ge.png",
  gc: "https://flagcdn.com/w320/gr.png",
  gua: "https://flagcdn.com/w320/gt.png",
  gu: "https://flagcdn.com/w320/gy.png",
  ha: "https://flagcdn.com/w320/ht.png",
  hon: "https://flagcdn.com/w320/hn.png",
  hug: "https://flagcdn.com/w320/hu.png",
  ind: "https://flagcdn.com/w320/in.png",
  indo: "https://flagcdn.com/w320/id.png",
  irk: "https://flagcdn.com/w320/iq.png",
  irn: "https://flagcdn.com/w320/ir.png",
  is: "https://flagcdn.com/w320/il.png",
  isl: "https://flagcdn.com/w320/is.png",
  it: "https://flagcdn.com/w320/it.png",
  jp: "https://flagcdn.com/w320/jp.png",
  jod: "https://flagcdn.com/w320/jo.png",
  kazj: "https://flagcdn.com/w320/kz.png",
  kir: "https://flagcdn.com/w320/kg.png",
  kuw: "https://flagcdn.com/w320/kw.png",
  lao: "https://flagcdn.com/w320/la.png",
  lib: "https://flagcdn.com/w320/lb.png",
  let: "https://flagcdn.com/w320/lv.png",
  liech: "https://flagcdn.com/w320/li.png",
  lit: "https://flagcdn.com/w320/lt.png",
  lux: "https://flagcdn.com/w320/lu.png",
  mal: "https://flagcdn.com/w320/my.png",
  mad: "https://flagcdn.com/w320/mv.png",
  mlt: "https://flagcdn.com/w320/mt.png",
  mld: "https://flagcdn.com/w320/md.png",
  mon: "https://flagcdn.com/w320/mc.png",
  mnt: "https://flagcdn.com/w320/me.png",
  mex: "https://flagcdn.com/w320/mx.png",
  nep: "https://flagcdn.com/w320/np.png",
  ni: "https://flagcdn.com/w320/ni.png",
  nor: "https://flagcdn.com/w320/no.png",
  om: "https://flagcdn.com/w320/om.png",
  pak: "https://flagcdn.com/w320/pk.png",
  pan: "https://flagcdn.com/w320/pa.png",
  par: "https://flagcdn.com/w320/py.png",
  pe: "https://flagcdn.com/w320/pe.png",
  pol: "https://flagcdn.com/w320/pl.png",
  prt: "https://flagcdn.com/w320/pt.png",
  psb: "https://flagcdn.com/w320/nl.png",
  rum: "https://flagcdn.com/w320/ro.png",
  ru: "https://flagcdn.com/w320/ru.png",
  sanlu: "https://flagcdn.com/w320/lc.png",
  sancyn: "https://flagcdn.com/w320/kn.png",
  sanvyg: "https://flagcdn.com/w320/vc.png",
  sing: "https://flagcdn.com/w320/sg.png",
  sir: "https://flagcdn.com/w320/sy.png",
  slan: "https://flagcdn.com/w320/lk.png",
  sp: "https://flagcdn.com/w320/es.png",
  sue: "https://flagcdn.com/w320/se.png",
  ske: "https://flagcdn.com/w320/ve.png",
  tur: "https://flagcdn.com/w320/tr.png",
  uc: "https://flagcdn.com/w320/ua.png",
  uk: "https://flagcdn.com/w320/gb.png",
  us: "https://flagcdn.com/w320/us.png",
  vat: "https://flagcdn.com/w320/va.png",
  viet: "https://flagcdn.com/w320/vn.png",
  ye: "https://flagcdn.com/w320/ye.png"
};

const enlaces = {
  tonoto: "https://youtu.be/sqK-jh4TDXo?si=XuSRrE5edpHiLcIa",
    afg: "https://es.wikipedia.org/wiki/Afganist%C3%A1n",
  alb: "https://es.wikipedia.org/wiki/Albania",
  and: "https://es.wikipedia.org/wiki/Andorra",
  antybarb: "https://es.wikipedia.org/wiki/Antigua_y_Barbuda",
  ar: "https://es.wikipedia.org/wiki/Argentina",
  arsau: "https://es.wikipedia.org/wiki/Arabia_Saudita",
  arm: "https://es.wikipedia.org/wiki/Armenia",
  aus: "https://es.wikipedia.org/wiki/Austria",
  aze: "https://es.wikipedia.org/wiki/Azerbaiy%C3%A1n",
  bah: "https://es.wikipedia.org/wiki/Bahamas",
  bar: "https://es.wikipedia.org/wiki/Bahrein",
  bel: "https://es.wikipedia.org/wiki/Belice",
  blg: "https://es.wikipedia.org/wiki/B%C3%A9lgica",
  birr: "https://es.wikipedia.org/wiki/Bielorrusia",
  bol: "https://es.wikipedia.org/wiki/Bolivia",
  bosher: "https://es.wikipedia.org/wiki/Bosnia_y_Herzegovina",
  brb: "https://es.wikipedia.org/wiki/Barbados",
  bra: "https://es.wikipedia.org/wiki/Brasil",
  brm: "https://es.wikipedia.org/wiki/Birmania",
  bru: "https://es.wikipedia.org/wiki/Brun%C3%A9i",
  but: "https://es.wikipedia.org/wiki/But%C3%A1n",
  cam: "https://es.wikipedia.org/wiki/Camboya",
  can: "https://es.wikipedia.org/wiki/Canad%C3%A1",
  cata: "https://es.wikipedia.org/wiki/Catar",
  chi: "https://es.wikipedia.org/wiki/Chile",
  chn: "https://es.wikipedia.org/wiki/China",
  cn: "https://es.wikipedia.org/wiki/Corea_del_Norte",
  cs: "https://es.wikipedia.org/wiki/Corea_del_Sur",
  col: "https://es.wikipedia.org/wiki/Colombia",
  cos: "https://es.wikipedia.org/wiki/Costa_Rica",
  cub: "https://es.wikipedia.org/wiki/Cuba",
  dinm: "https://es.wikipedia.org/wiki/Dinamarca",
  dom: "https://es.wikipedia.org/wiki/Dominica",
  ecu: "https://es.wikipedia.org/wiki/Ecuador",
  elsa: "https://es.wikipedia.org/wiki/El_Salvador",
  eu: "https://es.wikipedia.org/wiki/Estados_Unidos",
  esq: "https://es.wikipedia.org/wiki/Eslovaquia",
  esl: "https://es.wikipedia.org/wiki/Eslovenia",
  est: "https://es.wikipedia.org/wiki/Estonia",
  fin: "https://es.wikipedia.org/wiki/Finlandia",
  fil: "https://es.wikipedia.org/wiki/Filipinas",
  fr: "https://es.wikipedia.org/wiki/Francia",
  gc: "https://es.wikipedia.org/wiki/Grecia",
  gr: "https://es.wikipedia.org/wiki/Georgia",
  gra: "https://es.wikipedia.org/wiki/Grenada",
  gua: "https://es.wikipedia.org/wiki/Guatemala",
  gu: "https://es.wikipedia.org/wiki/Guyana",
  ha: "https://es.wikipedia.org/wiki/Hait%C3%AD",
  hon: "https://es.wikipedia.org/wiki/Honduras",
  hug: "https://es.wikipedia.org/wiki/Hungr%C3%ADa",
  ind: "https://es.wikipedia.org/wiki/India",
  indo: "https://es.wikipedia.org/wiki/Indonesia",
  irk: "https://es.wikipedia.org/wiki/Irak",
  irn: "https://es.wikipedia.org/wiki/Ir%C3%A1n",
  irl: "https://es.wikipedia.org/wiki/Irlanda",
  is: "https://es.wikipedia.org/wiki/Israel",
  isl: "https://es.wikipedia.org/wiki/Islandia",
  it: "https://es.wikipedia.org/wiki/Italia",
  jp: "https://es.wikipedia.org/wiki/Jap%C3%B3n",
  jod: "https://es.wikipedia.org/wiki/Jordania",
  kazj: "https://es.wikipedia.org/wiki/Kazajist%C3%A1n",
  kir: "https://es.wikipedia.org/wiki/Kirguist%C3%A1n",
  kos: "https://es.wikipedia.org/wiki/Kosovo",
  kuw: "https://es.wikipedia.org/wiki/Kuwait",
  lao: "https://es.wikipedia.org/wiki/Laos",
  let: "https://es.wikipedia.org/wiki/Letonia",
  liech: "https://es.wikipedia.org/wiki/Liechtenstein",
  lit: "https://es.wikipedia.org/wiki/Lituania",
  lux: "https://es.wikipedia.org/wiki/Luxemburgo",
  mal: "https://es.wikipedia.org/wiki/Malasia",
  mad: "https://es.wikipedia.org/wiki/Maldivas",
  mlt: "https://es.wikipedia.org/wiki/Malta",
  mld: "https://es.wikipedia.org/wiki/Moldavia",
  mon: "https://es.wikipedia.org/wiki/M%C3%B3naco",
  mnt: "https://es.wikipedia.org/wiki/Montenegro",
  mex: "https://es.wikipedia.org/wiki/M%C3%A9xico",
  nep: "https://es.wikipedia.org/wiki/Nepal",
  ni: "https://es.wikipedia.org/wiki/Nicaragua",
  nor: "https://es.wikipedia.org/wiki/Noruega",
  om: "https://es.wikipedia.org/wiki/Om%C3%A1n",
  pak: "https://es.wikipedia.org/wiki/Pakist%C3%A1n",
  pan: "https://es.wikipedia.org/wiki/Panam%C3%A1",
  par: "https://es.wikipedia.org/wiki/Paraguay",
  pe: "https://es.wikipedia.org/wiki/Per%C3%BA",
  pol: "https://es.wikipedia.org/wiki/Polonia",
  prt: "https://es.wikipedia.org/wiki/Portugal",
  psb: "https://es.wikipedia.org/wiki/Pa%C3%ADses_Bajos",
  rch: "https://es.wikipedia.org/wiki/Rep%C3%BAblica_Checa",
  redom: "https://es.wikipedia.org/wiki/Rep%C3%BAblica_Dominicana",
  rum: "https://es.wikipedia.org/wiki/Ruman%C3%ADa",
  ru: "https://es.wikipedia.org/wiki/Rusia",
  sing: "https://es.wikipedia.org/wiki/Singapur",
  sir: "https://es.wikipedia.org/wiki/Siria",
  slan: "https://es.wikipedia.org/wiki/Sri_Lanka",
  sanlu: "https://es.wikipedia.org/wiki/Santa_Luc%C3%ADa",
  sancyn: "https://es.wikipedia.org/wiki/San_Crist%C3%B3bal_y_Nevis",
  sanvyg: "https://es.wikipedia.org/wiki/San_Vicente_y_las_Granadinas",
  smar: "https://es.wikipedia.org/wiki/San_Marino",
  sp: "https://es.wikipedia.org/wiki/Espa%C3%B1a",
  suri: "https://es.wikipedia.org/wiki/Surinam",
  ske: "https://es.wikipedia.org/wiki/Venezuela",
  tay: "https://es.wikipedia.org/wiki/Tayikist%C3%A1n",
  tai: "https://es.wikipedia.org/wiki/Tailandia",
  tior: "https://es.wikipedia.org/wiki/Timor_Leste",
  trkm: "https://es.wikipedia.org/wiki/Turkmenist%C3%A1n",
  trq: "https://es.wikipedia.org/wiki/Turqu%C3%ADa",
  tur: "https://es.wikipedia.org/wiki/Turqu%C3%ADa",
  uc: "https://es.wikipedia.org/wiki/Ucrania",
  uk: "https://es.wikipedia.org/wiki/Reino_Unido",
  uru: "https://es.wikipedia.org/wiki/Uruguay",
  vat: "https://es.wikipedia.org/wiki/Vaticano",
  viet: "https://es.wikipedia.org/wiki/Vietnam",
  ye: "https://es.wikipedia.org/wiki/Yemen"
};

// Consigue la informacion enviada por medio del "value" de los selects //
const selectIzq = document.getElementById("select-izq");
const selectDer = document.getElementById("select-der");
const imgIzq = document.getElementById("bandera-izq");
const imgDer = document.getElementById("bandera-der");
const linkIzq = document.getElementById("link-izq");
const linkDer = document.getElementById("link-der");


// Cuando el select izquierdo cambia //
selectIzq.addEventListener("change", () => {
  const pais = selectIzq.value;         // Obtiene el valor seleccionado
  imgIzq.src = banderas[pais];          // Cambia la imagen de la bandera por medio del index del arreglo
  linkIzq.href = enlaces[pais] || "#";  // Cambia el enlace correspondiente o pone "#" si no existe
});

// Cuando el select derecho cambia //
selectDer.addEventListener("change", () => {
  const pais = selectDer.value;
  imgDer.src = banderas[pais];  
  linkDer.href = enlaces[pais] || "#";
});

// Inicializa las imágenes al cargar la página
window.addEventListener("DOMContentLoaded", () => {
  const paisIzq = selectIzq.value;
  const paisDer = selectDer.value;
  imgIzq.src = banderas[paisIzq];
  imgDer.src = banderas[paisDer];
  linkIzq.href = enlaces[paisIzq] || "#";
  linkDer.href = enlaces[paisDer] || "#";
});
