// Relación de país -> bandera (puedes ir agregando más)
const banderas = {
  tonoto: "https://imgs.search.brave.com/R26FDVFLl62qiPqEiQ-ZSqddOrZdJINx6wH2D4i8_BM/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2JhL2Ey/LzNjL2JhYTIzY2Nm/YjkwMzg2MmFmMGVi/NTRhNzJmNzEzMDRm/LmpwZw",
  antybarb: "https://www.banderas-mundo.es/data/flags/h160/ag.webp",
  ar: "https://flagcdn.com/w320/ar.png",
  bah: "https://flagcdn.com/w320/bs.png",
  brb: "https://flagcdn.com/w320/bb.png",
  bel:"https://www.banderas-mundo.es/data/flags/h80/bz.webp",
  bol: "https://flagcdn.com/w320/bo.png",
  bra: "https://flagcdn.com/w320/br.png",
  can: "https://flagcdn.com/w320/ca.png",
  chi: "https://flagcdn.com/w320/cl.png",
  col: "https://flagcdn.com/w320/co.png",
  cos: "https://flagcdn.com/w320/cr.png",
  cub: "https://flagcdn.com/w320/cu.png",
  dom: "https://flagcdn.com/w320/do.png",
  ecu: "https://flagcdn.com/w320/ec.png",
  elsa: "https://flagcdn.com/w320/sv.png",
  eu:"https://www.banderas-mundo.es/data/flags/h80/us.webp",
  gra: "https://www.banderas-mundo.es/data/flags/h80/gd.webp",
  gua: "https://flagcdn.com/w320/gt.png",
  gu: "https://flagcdn.com/w320/gy.png",
  ha: "https://flagcdn.com/w320/ht.png",
  hon: "https://flagcdn.com/w320/hn.png",
  jam: "https://flagcdn.com/w320/jm.png",
  mex: "https://www.banderas-mundo.es/data/flags/h160/mx.webp",
  ni: "https://flagcdn.com/w320/ni.png",
  pan: "https://flagcdn.com/w320/pa.png",
  par: "https://flagcdn.com/w320/py.png",
  pe: "https://flagcdn.com/w320/pe.png",
  redom: "https://www.banderas-mundo.es/data/flags/h80/do.webp",
  sancyn: "https://flagcdn.com/w320/kn.png",
  sanvyg: "https://www.banderas-mundo.es/data/flags/h80/vc.webp",
  sanlu: "https://www.banderas-mundo.es/data/flags/h80/lc.webp",
  suri: "https://flagcdn.com/w320/sr.png",
  trito: "https://flagcdn.com/w320/tt.png",
  uru: "https://flagcdn.com/w320/uy.png",
  ske: "https://flagcdn.com/w320/ve.png",
  afg: "https://flagcdn.com/w320/af.png",
  arsau: "https://www.banderas-mundo.es/data/flags/h80/sa.webp",
  arm: "https://flagcdn.com/w320/am.png",
  aze: "https://flagcdn.com/w320/az.png",
  ban: "https://flagcdn.com/w320/bd.png",
  bar: "https://www.banderas-mundo.es/data/flags/h80/bh.webp",
  brm:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/250px-Flag_of_Myanmar.svg.png",
  bru: "https://flagcdn.com/w320/bn.png",
  but: "https://flagcdn.com/w320/bt.png",
  cam: "https://flagcdn.com/w320/kh.png",
  cata: "https://flagcdn.com/w320/qa.png",
  chn: "https://flagcdn.com/w320/cn.png",
  cn: "https://www.banderas-mundo.es/data/flags/h80/kp.webp",
  cs:"https://www.banderas-mundo.es/data/flags/h80/kr.webp",
  emaru: "https://flagcdn.com/w320/ae.png",
  fil: "https://flagcdn.com/w320/ph.png",
  ind: "https://flagcdn.com/w320/in.png",
  indo: "https://flagcdn.com/w320/id.png",
  irk: "https://www.banderas-mundo.es/data/flags/h80/iq.webp",
  irn: "https://flagcdn.com/w320/ir.png",
  is: "https://flagcdn.com/w320/il.png",
  jp: "https://flagcdn.com/w320/jp.png",
  jod: "https://flagcdn.com/w320/jo.png",
  kazj: "https://flagcdn.com/w320/kz.png",
  kir: "https://flagcdn.com/w320/kg.png",
  kuw: "https://flagcdn.com/w320/kw.png",
  lao: "https://flagcdn.com/w320/la.png",
  lib: "https://flagcdn.com/w320/lb.png",
  mal: "https://flagcdn.com/w320/my.png",
  mad: "https://www.banderas-mundo.es/data/flags/h80/mv.webp",
  mon: "https://flagcdn.com/w320/mn.png",
  nep: "https://flagcdn.com/w320/np.png",
  om: "https://flagcdn.com/w320/om.png",
  pak: "https://flagcdn.com/w320/pk.png",
  sing: "https://flagcdn.com/w320/sg.png",
  sir:"https://www.banderas-mundo.es/data/flags/h80/sy.webp",
  slan: "https://flagcdn.com/w320/lk.png",
  tay: "https://www.banderas-mundo.es/data/flags/h80/tj.webp",
  tai: "https://flagcdn.com/w320/th.png",
  tior: "https://www.banderas-mundo.es/data/flags/h80/tl.webp",
  trkm: "https://flagcdn.com/w320/tm.png",
  trq: "https://flagcdn.com/w320/tr.png",
  uzb: "https://flagcdn.com/w320/uz.png",
  viet: "https://flagcdn.com/w320/vn.png",
  ye: "https://flagcdn.com/w320/ye.png",
  alb: "https://flagcdn.com/w320/al.png",
  hit: "https://www.banderas-mundo.es/data/flags/h80/de.webp",
  and: "https://flagcdn.com/w320/ad.png",
  aus: "https://www.banderas-mundo.es/data/flags/h80/at.webp",
  azer: "https://flagcdn.com/w320/az.png",
  blg: "https://www.banderas-mundo.es/data/flags/h80/be.webp",
  birr: "https://flagcdn.com/w320/by.png",
  bosher: "https://flagcdn.com/w320/ba.png",
  bulg: "https://www.banderas-mundo.es/data/flags/h80/bg.webp",
  chp: "https://flagcdn.com/w320/cy.png",
  croc: "https://flagcdn.com/w320/hr.png",
  dinm: "https://flagcdn.com/w320/dk.png",
  esq: "https://www.banderas-mundo.es/data/flags/h80/sk.webp",
  esl: "https://www.banderas-mundo.es/data/flags/h80/si.webp",
  sp: "https://flagcdn.com/w320/es.png",
  est: "https://flagcdn.com/w320/ee.png",
  fin: "https://flagcdn.com/w320/fi.png",
  fr: "https://flagcdn.com/w320/fr.png",
  gr: "https://www.banderas-mundo.es/data/flags/h80/ge.webp",
  gc: "https://flagcdn.com/w320/gr.png",
  hug: "https://flagcdn.com/w320/hu.png",
  irl: "https://flagcdn.com/w320/ie.png",
  isl: "https://flagcdn.com/w320/is.png",
  it: "https://flagcdn.com/w320/it.png",
  kos: "https://flagcdn.com/w320/xk.png",
  let: "https://flagcdn.com/w320/lv.png",
  liech: "https://flagcdn.com/w320/li.png",
  lit: "https://flagcdn.com/w320/lt.png",
  lux: "https://flagcdn.com/w320/lu.png",
  mlt: "https://flagcdn.com/w320/mt.png",
  mld: "https://flagcdn.com/w320/md.png",
  mon: "https://flagcdn.com/w320/mc.png",
  mnt: "https://flagcdn.com/w320/me.png",
  nor: "https://flagcdn.com/w320/no.png",
  psb: "https://www.banderas-mundo.es/data/flags/h80/nl.webp",
  pol: "https://flagcdn.com/w320/pl.png",
  prt: "https://flagcdn.com/w320/pt.png",
  uk: "https://flagcdn.com/w320/gb.png",
  rch: "https://www.banderas-mundo.es/data/flags/h80/cz.webp",
  rum: "https://flagcdn.com/w320/ro.png",
  ru: "https://flagcdn.com/w320/ru.png",
  smar:"https://www.banderas-mundo.es/data/flags/h80/sm.webp",
  srb: "https://flagcdn.com/w320/rs.png",
  sue: "https://flagcdn.com/w320/se.png",
  siz: "https://flagcdn.com/w320/ch.png",
  tur: "https://flagcdn.com/w320/tr.png",
  uc: "https://flagcdn.com/w320/ua.png",
  vat: "https://flagcdn.com/w320/va.png",
};

// Referencias a selects e imágenes
const selectIzq = document.getElementById("select-izq");
const selectDer = document.getElementById("select-der");
const imgIzq = document.getElementById("bandera-izq");
const imgDer = document.getElementById("bandera-der");

// Cuando cambie la opción del select izquierdo
selectIzq.addEventListener("change", () => {
  const pais = selectIzq.value;
  imgIzq.src = banderas[pais];
});

// Cuando cambie la opción del select derecho
selectDer.addEventListener("change", () => {
  const pais = selectDer.value;
  imgDer.src = banderas[pais];
});
// Inicializar las imágenes al cargar la página
window.addEventListener("DOMContentLoaded", () => {
  imgIzq.src = banderas[selectIzq.value];
  imgDer.src = banderas[selectDer.value];
});